name: Check

on:
  push:
    paths:
      - '.github/workflows/check.yml'
      - 'src/**/*.svelte'
      - 'src/**/*.ts'
      - '.editorconfig'
      - 'biome.json'
      - 'bun.lockb'
      - 'package.json'
      - 'tsconfig.json'
      - 'vite.config.ts'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bunx biome check --verbose .
