name: CI

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'src/**/*.ts'
      - '.editorconfig'
      - 'eslint.config.js'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'vite.config.ts'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm run format:check
