name: Check for un-formatted files

on:
  push:
    paths:
      - '.editorconfig'
      - 'biome.json'
      - '**/*.js'
      - '**/*.json'
      - '**/*.md'
      - '**/*.svelte'
      - '**/*.ts'
      - '**/*.yml'

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run format:check
