name: Lint

on:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - 'src/**/*.ts'
      - '.editorconfig'
      - 'eslint.config.js'
      - 'package.json'
      - 'tsconfig.json'
      - 'vite.config.ts'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 21.1.0
      - run: npm ci
      - run: npm run lint
