name: Lint

on:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - 'src/**/*.ts'
      - '.editorconfig'
      - 'eslint.config.js'
      - 'package.json'
      - 'tsconfig.json'
      - 'vite.config.ts'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run lint
