name: Release obsidian plugin

on:
  push:
    tags:
      - '[0-9].[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/main.js,dist/styles.css,manifest.json'
          body: |
            Please refer to [CHANGELOG.md](https://github.com/0918nobita/obsidian-zhongwen-block/blob/main/CHANGELOG.md) for details.
          token: ${{ secrets.GH_RELEASE_TOKEN }}
